language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.dev.txt
before_script:
  - export PYPACT=$PWD
  - export PYTHONPATH=$PYTHONPATH:$PYPACT/pypact
script:
  - pip3 install -e $PYPACT
  - python $PYPACT/setup.py test
  - bash scripts/run_coverage
  - python scripts/run_pylint.py -j4 --rcfile=.pylintrc --output-format=text --score-threshold=4 pypact &> pylint.txt
  - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
  - echo "Pylint score:" $score
  - fispactconverter.py $PYPACT/reference/test31.out test31.json
# run examples (no plotting)
  - cd $PYPACT/examples
  - python changefilesfile.py
  - python doserates.py
  - python outputjson.py
  - python readfilesfile.py
  - python rundatajson.py
  - python printlib5.py
  - python tocsv.py
  - python writefilesfile.py
  - python writefluxesfile.py
  - python writeinputfile.py
  - cd $PYPACT
after_success:
  - codecov
