language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.dev.txt
before_script:
  - export PYPACT=$PWD
  - export PYTHONPATH=$PYTHONPATH:$PYPACT/pypact
script:
  - pip3 install -e $PYPACT
  - python $PYPACT/setup.py test
  - bash scripts/run_coverage
  - python scripts/run_pylint.py -j4 --rcfile=.pylintrc --output-format=text --score-threshold=4 pypact &> pylint.txt
  - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
  - echo "Pylint score:" $score
  - fispactconverter.py $PYPACT/reference/test31.out test31.json
# run examples (no plotting)
  - cd $PYPACT/examples
  - python simple/doserates.py
  - python simple/outputjson.py
  - python simple/rundatajson.py
  - python simple/readfilesfile.py
  - python inputcreation/changefilesfile.py
  - python inputcreation/writefilesfile.py
  - python inputcreation/writefluxesfile.py
  - python inputcreation/writeinputfile.py
  - python printlib/printlib5.py
  - python csv/tocsv.py
  - cd $PYPACT
after_success:
  - codecov
